### ISSUE TITLE
Something wrong with the GET request

### ISSUE THREAD

**Issue by MASIJUN99** [jumangee/HTTPClient32#1]
Hi jumangee, Im a java coder.

Recently i used esp32 to send a GET http request, i used your lib and there was some errors.

Here is my Arduino code:

![image](https://user-images.githubusercontent.com/58580226/154727826-705d788c-aac1-4d13-978b-d405d873993d.png)

Very easy to understand, it likes your sample code, but here is the console about my java program.

![image](https://user-images.githubusercontent.com/58580226/154728093-e9b384f2-eae8-4fe3-93f2-aeace816dd21.png)

Maybe there was something wrong.

By the way, here is my Serial output

![image](https://user-images.githubusercontent.com/58580226/154728196-fecf2940-0d91-4fe8-952d-1bb10a1a21b3.png)

The debug level of AduinoIDE is 'debug'

**Comment by MASIJUN99** [comment]
I have already done this job :) welcome pull my code

**Comment by jumangee** [comment]
Sorry, but I really don't see the difference, what changed?

**Comment by MASIJUN99** [comment]
The error occurred in when create a ‘HTTPRequest’.&nbsp;
In your all args constructor, you let ‘this-&gt;method=HTTP_GET ? “GET” : “POST”’ I change this logic.
In src/HTTPClient32Client.h



發自我的iPhone


------------------ Original ------------------
From: jumangee ***@***.***&gt;
Date: Sat,Feb 19,2022 3:14 AM
To: jumangee/HTTPClient32 ***@***.***&gt;
Cc: MASIJUN ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [jumangee/HTTPClient32] Something wrong with the GET request (Issue #1)





 
Sorry, but I really don't see the difference, what changed?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jumangee** [comment]
Oh! I see now! Thank you very much!

**Comment by MASIJUN99** [comment]
I guess you will use ArduinoJson to parse json string in your Arduino program, but I got a problem when I parse my json.
Because the json contains bool arg without brackets I guess.
Like {“deleted”:false}. How do you solve that? I have no time to verify that because of 3:30am in china now. I’ll go to sleep.



發自我的iPhone


------------------ Original ------------------
From: jumangee ***@***.***&gt;
Date: Sat,Feb 19,2022 3:25 AM
To: jumangee/HTTPClient32 ***@***.***&gt;
Cc: MASIJUN ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [jumangee/HTTPClient32] Something wrong with the GET request (Issue #1)





 
Oh! I see now! Thank you very much!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jumangee** [comment]
Yep, I'am using ArduinoJson in Telegram library, which isn't pushed to github yet. Your json seems correct, bool values should not be in brackets, only "key" are. May be you have allocated too small memory for decoding?
I'am using 2KB memory for all responses and it works for now)
```
DynamicJsonDocument* doc = new DynamicJsonDocument(2048);
DeserializationError error = deserializeJson(*doc, result.c_str());

if (!error && doc->containsKey(F("ok")) && doc->containsKey(F("result"))) {
    json = doc;

    return json->getMember(F("ok")).as<bool>();
}
```

If this won't help you, paste full your json body here, try to figure out what is wrong

**Comment by MASIJUN99** [comment]
Sorry to reply too late. i slept last night.

```text
{"createTime":"2022-02-19 13:13:40","updateTime":"2022-02-19 13:13:40","deleted":false,"id":23,"locationId":101010100,"obsTime":"2022-02-19 13:06:00","temp":1.0,"feelsLike":-9.0,"weatherType":"SUNNY","windDir":"西风","windScale":6.0,"windSpeed":40.0,"humidity":16.0,"precip":0.0,"pressure":1030.0}

deserializeJson() failed: InvalidInput
```

Here is my com output. I used Serial.println to print json string on screen.

But it was success when i try this:

```text
String input = "{\"createTime\":\"2022-02-19 02:04:10\",\"updateTime\":\"2022-02-19 02:04:10\",\"deleted\":false,\"id\":7,\"locationId\":101010100,\"obsTime\":\"2022-02-19 01:54:00\",\"temp\":-6.0,\"feelsLike\":-12.0,\"weatherType\":\"CLEAR\",\"windDir\":\"北风\",\"windScale\":3.0,\"windSpeed\":18.0,\"humidity\":25.0,\"precip\":0.0,\"pressure\":1032.0}";


  // Deserialize the JSON document
  DeserializationError error = deserializeJson(doc, input);

  // Test if parsing succeeds.
  if (error) {
    Serial.print(F("deserializeJson() failed: "));
    Serial.println(error.f_str());
    return;
  }
```
im so confused!

**Comment by MASIJUN99** [comment]
This is my code in first condition.

```text
      Serial.println("Response GET: ");
      String json = client->getResponseString();
      Serial.println(json);

      // String input = "{\"createTime\":\"2022-02-19 02:04:10\",\"updateTime\":\"2022-02-19 02:04:10\",\"deleted\":false,\"id\":7,\"locationId\":101010100,\"obsTime\":\"2022-02-19 01:54:00\",\"temp\":-6.0,\"feelsLike\":-12.0,\"weatherType\":\"CLEAR\",\"windDir\":\"北风\",\"windScale\":3.0,\"windSpeed\":18.0,\"humidity\":25.0,\"precip\":0.0,\"pressure\":1032.0}";

      DynamicJsonDocument doc(4096);  // JSON
      DeserializationError error = deserializeJson(doc, json);

      // Test if parsing succeeds.
      if (error) {
        Serial.print(F("deserializeJson() failed: "));
        Serial.println(error.f_str());
        return;
      }
```

**Comment by jumangee** [comment]
Yeah, strange, json validator says input is valid
try to use "deserializeJson(doc, json.c_str());" it's recommended
Also, can you print json variable content? maybe something wrong with input?
add after Serial.println(error.f_str()); - Serial.println(json);

**Comment by MASIJUN99** [comment]
I found some clue maybe, How to RUN ARDUINO program in debug mode?

I used your lib to get json string.

There do error in json string. I print it like that!

```text
12e
{"createTime":"2022-02-19 19:13:21","updateTime":"2022-02-19 19:13:21","deleted":false,"id":24,"locationId":101010100,"obsTime":"2022-02-19 18:56:00","temp":0.0,"feelsLike":-5.0,"weatherType":"CLEAR","windDir":"西北风","windScale":3.0,"windSpeed":14.0,"humidity":18.0,"precip":0.0,"pressure":1028.0}
0
```
what is '12e' and '0'?

**Comment by jumangee** [comment]
I don't know what is it)) can you get me in pvt messages full url and auth? i'll try to figure out what's wrong with it

**Comment by jumangee** [comment]
Oops, github has no pvt boxes, send me it to jumangee@inbox.ru

**Comment by MASIJUN99** [comment]
I had sent, check your box :)
